### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by IqraMahmood**
Updat the python data exploration code file

### CODE REVIEW

**Comment by MartinSeeler** [comment]
HI @IqraMahmood, thanks for the additions!

Some minor points:
- `unique()` is described twice now
- Can you find a better headline for `value_counts`? Maybe `Value counts`?
- Please adjust the other jupyter notebook `Exploring Datasets Yourself.ipynb` as well, I tried to keep them in sync

After that, I'm happy to merge 👍

**Comment by IqraMahmood** [comment]
Thank you @MartinSeeler for your the reply. 
I will update and add the points you mention.

**Comment by IqraMahmood** [comment]
@MartinSeeler I have updated `Exploring Datasets Yourself.ipynb`. Have a look at it.

**Comment by MartinSeeler** [comment]
Hey @IqraMahmood, thanks for your contribution. It is hard for me to see what you've done because all of your commit messages are the same. 

The `Exploring Datasets Yourself.ipynb` file was meant to be an exercise notebook file. Therefore, the cells should be empty. But the exercises content should match the content from the `Exploring Datasets.ipynb` notebook file.

Also, there are still headlines like `value_counts`, which I asked you to change for a better title.

As long as the cells for the exercise notebook are pre-filled and the titles are not updated, I can not merge this pull request.

**Comment by IqraMahmood** [comment]
HI @MartinSeeler  
Sorry for the inconvenience. I am new to GitHub so could not commit properly.
Could you please confirm that I only need to update the Exploring Datasets.ipynb file? And Exploring Datasets Yourself.ipynb should be kept empty.

**Comment by MartinSeeler** [comment]
> Sorry for the inconvenience. I am new to GitHub so could not commit properly.

Here are some useful resources to [get started with Github](https://docs.github.com/en/get-started/quickstart/hello-world) and [how to write good commit messages](https://reflectoring.io/meaningful-commit-messages/).

> Could you please confirm that I only need to update the Exploring Datasets.ipynb file? And Exploring Datasets Yourself.ipynb should be kept empty.

If you want to make additions to this repository, you have to change **both** files.

`Exploring Datasets.ipynb` is a guided notebook, where you can follow along and read about how to explore datasets with Python. The `Exploring Datasets Yourself.ipynb` notebook is an exercise for the reader, to test what they have learned.

If you add a section about a new topic to `Exploring Datasets.ipynb`, you should also add an **empty exercise** section about this new topic to `Exploring Datasets Yourself.ipynb`, so that the reader can try it by himself/herself.

You have commited the `Exploring Datasets Yourself.ipynb` with **your solutions**. This makes the whole file useless for others, because everyone checking out this repo can not do the exercise and will see **your solutions** instead. To make it available for everyone, please remove the cell input from the exercise but keep the tasks for newly added sections.

Also, after reviewing your pull request the first time, I've asked you to change a single headline. After that, I would have merged it. But instead you added a lot more new stuff to it. This makes it very hard to keep up with the merge request, because I have to review it every time again. It would therefore be very helpful if you provide **better commit messages**, so that I can have an idea of what you have added.

I hope this clarification will help you make better merge requests and provide you with some starting points on how to improve your journey as an open source contributor 🚀

**Pull request closed without merging**
